# Generated by Django 5.2.8 on 2025-12-04 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('durasi_hari', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Baru Masuk'), ('PROCESS', 'Sedang Dikerjakan'), ('READY', 'Selesai / Siap Ambil'), ('COMPLETED', 'Sudah Diambil')], default='PENDING', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='operasional.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk_sepatu', models.CharField(max_length=50)),
                ('warna', models.CharField(max_length=50)),
                ('catatan', models.TextField(blank=True)),
                ('foto_sebelum', models.ImageField(upload_to='foto_sepatu/before/')),
                ('foto_sesudah', models.ImageField(blank=True, null=True, upload_to='foto_sepatu/after/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operasional.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operasional.service')),
            ],
        ),
    ]
