# Generated by Django 5.2.8 on 2025-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tanggal_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
