# Generated by Django 5.2.8 on 2025-12-14 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0002_order_tanggal_selesai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengeluaran', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=0, max_digits=12)),
                ('kategori', models.CharField(choices=[('BAHAN', 'Bahan Baku (Sabun/Cat/Parfum)'), ('OPERASIONAL', 'Operasional (Listrik/Bensin/Makan)'), ('MARKETING', 'Iklan/Promo/Stiker'), ('GAJI', 'Gaji Karyawan'), ('LAINNYA', 'Lain-lain')], default='BAHAN', max_length=20)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='metode_pembayaran',
            field=models.CharField(choices=[('CASH', 'Cash / Tunai'), ('TRANSFER', 'Transfer Bank / QRIS'), ('UNPAID', 'Belum Bayar (Hutang)')], default='CASH', max_length=20),
        ),
    ]
