# Generated by Django 5.2.8 on 2025-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0003_pengeluaran_order_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Baru Masuk'), ('PROCESS', 'Sedang Dikerjakan'), ('READY', 'Selesai / Siap Ambil'), ('COMPLETED', 'Sudah Diambil')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tanggal_selesai_item',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
