# Generated by Django 5.2.8 on 2025-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0004_orderitem_status_orderitem_tanggal_selesai_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='sub_kategori',
            field=models.CharField(blank=True, help_text='e.g., Sabun, Cat Merah, Bensin, dll', max_length=100, null=True),
        ),
    ]
